name: FatPack
main: com.github.fatfrido.fatpack.FatPack
version: 1.0
author: Fatfrido

depend: [Vault, PermissionsEx]

commands:
  day:
    description: Let a new day begin!
    usage: /day <worldname>
    aliases: [tag]
    permission: day.use
  buy:
    description: Use your money to buy something.
    usage: /buy certificate <certificatename>
    permission: buy.certificate
  certificate:
    description: All about certificates
    aliases: [certificates]